### ISSUE TITLE
what's the difference between get_context_emb() and get_context_emb_sim()?

### ISSUE THREAD

**Issue by dragen1860** [TencentARC/ST-LLM#13]
Dear all:
  I noticed that you use d `get_context_emb_sim()` in `demo.py` but used `get_context_emb()` in demo_gradio.py. I wonder both the two function are embedding the image&text tokens, what is  the difference?  thank you.

**Comment by farewellthree** [comment]
Both demo and demo_gradio use get_context_emb_sim. get_context_emb_sim is suitable for InstructBLIP, while get_context_emb is suitable for MiniGPT-4.
