### ISSUE TITLE
how to modify the code to support llama3?

### ISSUE THREAD

**Issue by dragen1860** [TencentARC/ST-LLM#16]
Hi, dear all:
  Thought the paper did superior performance with only vicuna-7b models, I want to exploere the potentials on stronger LLMs, such as llama3 or Yi.  Anyone give some tips on how to modify the code to support llama3 training with  STLLM datasets. Thank you ...

**Comment by farewellthree** [comment]
The good performance of video LLMs relies on image LLMs, and the role of the large language model itself is not that significant. Currently, the best image LLM is LLaVA1.6. We are now conducting new experiments based on LLaVA1.6 and will update the code trained on LLaVA1.6 soon.
