### ISSUE TITLE
Which GPT-3.5 version did you use during evaluation?

### ISSUE THREAD

**Issue by SCZwangxiao** [TencentARC/ST-LLM#19]

**Comment by farewellthree** [comment]
We used the official GPT-3.5-Turbo, which seems to point to GPT-3.5-Turbo-0613 during the period from 2023/06/26 to 2024/02/15. However, this version has just been deprecated by OpenAI. The current GPT-3.5-Turbo-0125 lowers the results, while GPT-3.5-Turbo-16k raises the results.
