### ISSUE TITLE
MVBench测试结果不一致

### ISSUE THREAD

**Issue by emmating12** [TencentARC/ST-LLM#3]
您好，我在本地配置的EVA ViT-g+InstructBLIP+Vicuna1.1模型，在MVBench上测试结果为35.45%，具体测试结果见附件，能帮忙看下是哪里出的问题吗？
[instructblipbase_stllm_qa_mvbench_fps1.json](https://github.com/TencentARC/ST-LLM/files/14915461/instructblipbase_stllm_qa_mvbench_fps1.json)

**Comment by farewellthree** [comment]
是给的权重吗，另一个issue的老哥用提供的ckpt测是正常的，训练时的ckpt出了点问题

**Comment by emmating12** [comment]
> 是给的权重吗，另一个issue的老哥用提供的ckpt测是正常的，训练时的ckpt出了点问题

https://github.com/TencentARC/ST-LLM/blob/main/trainval.md 您好 我是按照这个页面修改的

**Comment by emmating12** [comment]
model:
  arch: st_llm_hf
  model_type: instructblip_vicuna0_btadapter
  use_grad_checkpoint: True
  max_txt_len: 256
  end_sym: "###"
  video_input: "all"
  llama_model: '/root/qfs1/weights/vicuna-7b-v1.1'
  ckpt: '/root/qfs1/weights/ST-LLM/instruct_blip_vicuna7b_trimmed.pth'
  q_former_model: '/root/qfs1/weights/ST-LLM/instruct_blip_vicuna7b_trimmed.pth'
  qformer_text_input: True
  freeze_LLM: False
  use_mask : True
  mvm_decode: True

**Comment by farewellthree** [comment]
35.45%似乎是instructblip baseline的效果。QA的权重load正确吗？可以在stllm/models/st_llm.py 201行打个断点看看。

**Comment by emmating12** [comment]
> 35.45%似乎是instructblip baseline的效果。QA的权重load正确吗？可以在stllm/models/st_llm.py 201行打个断点看看。

您好  QA的权重是不是下载这个呢  https://huggingface.co/farewellthree/ST_LLM_weight/tree/main/QA_weight
