### ISSUE TITLE
Cuda Version

### ISSUE THREAD

**Issue by saroo25** [TencentARC/ST-LLM#6]
Hello,
I am trying to run the scripts on a machine with CUDA 11.7 installed, but I keep getting the error :
RuntimeError: The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

So I was wondering which version of CUDA I should install to solve. Thanks in advance for your help.

**Comment by farewellthree** [comment]
We adopt CUDA 11.8 with pytorch 2.0
