### ISSUE TITLE
HF weights

### ISSUE THREAD

**Issue by mutonix** [TencentARC/ST-LLM#7]
Many thanks to the great contribution! What is the difference between the QA_weight and Conversation_weight in the huggingface repo?

**Comment by farewellthree** [comment]
QA_weight uses almost the same datasets as VideoChat2. Conversation_weight enables the global-local module and is mainly trained on caption datasets, which works better on conversation and long video input.

**Comment by mutonix** [comment]
Got it! Thanks for your reply :)
